### ISSUE TITLE
Adjust font size

### ISSUE THREAD

**Issue by achou11** [achou11/andrew-chou#4]
Add the following rules:

```css
body {
  font-size: 1.1rem;
}

 <!-- on mobile only? -->
footer {
  font-size: 1rem;
}
```
